-- 초기 카탈로그 시드 (created_by null = 시스템 시드)

insert into public.catalog_items (kind, name, slug, url) values
  ('harness', 'Claude Code',    'claude-code',    'https://claude.com/claude-code'),
  ('harness', 'Codex CLI',      'codex-cli',      'https://github.com/openai/codex'),
  ('harness', 'Cursor',         'cursor',         'https://cursor.com'),
  ('harness', 'Gemini CLI',     'gemini-cli',     'https://github.com/google-gemini/gemini-cli'),
  ('harness', 'Aider',          'aider',          'https://aider.chat'),
  ('harness', 'opencode',       'opencode',       'https://opencode.ai'),
  ('harness', 'Cline',          'cline',          'https://cline.bot'),
  ('harness', 'GitHub Copilot', 'github-copilot', 'https://github.com/features/copilot'),
  ('model', 'Claude Opus',    'claude-opus',    'https://www.anthropic.com/claude'),
  ('model', 'Claude Sonnet',  'claude-sonnet',  'https://www.anthropic.com/claude'),
  ('model', 'Claude Haiku',   'claude-haiku',   'https://www.anthropic.com/claude'),
  ('model', 'GPT-5',          'gpt-5',          'https://openai.com'),
  ('model', 'GPT-5-Codex',    'gpt-5-codex',    'https://openai.com'),
  ('model', 'Gemini 2.5 Pro', 'gemini-2-5-pro', 'https://deepmind.google/models/gemini'),
  ('model', 'DeepSeek',       'deepseek',       'https://deepseek.com'),
  ('model', 'Qwen',           'qwen',           'https://qwen.ai'),
  ('mcp', 'Playwright MCP',      'playwright-mcp',      'https://github.com/microsoft/playwright-mcp'),
  ('mcp', 'Context7',            'context7',            'https://github.com/upstash/context7'),
  ('mcp', 'GitHub MCP',          'github-mcp',          'https://github.com/github/github-mcp-server'),
  ('mcp', 'Notion MCP',          'notion-mcp',          'https://github.com/makenotion/notion-mcp-server'),
  ('mcp', 'Filesystem MCP',      'filesystem-mcp',      'https://github.com/modelcontextprotocol/servers'),
  ('mcp', 'Supabase MCP',        'supabase-mcp',        'https://github.com/supabase-community/supabase-mcp'),
  ('mcp', 'Sentry MCP',          'sentry-mcp',          'https://docs.sentry.io/product/sentry-mcp'),
  ('mcp', 'Chrome DevTools MCP', 'chrome-devtools-mcp', 'https://github.com/ChromeDevTools/chrome-devtools-mcp'),
  ('skill', 'superpowers',   'superpowers',   'https://github.com/obra/superpowers'),
  ('skill', 'skill-creator', 'skill-creator', 'https://github.com/anthropics/skills'),
  ('editor', 'VS Code',        'vs-code',        'https://code.visualstudio.com'),
  ('editor', 'Cursor',         'cursor',         'https://cursor.com'),
  ('editor', 'Zed',            'zed',            'https://zed.dev'),
  ('editor', 'Neovim',         'neovim',         'https://neovim.io'),
  ('editor', 'JetBrains IDEs', 'jetbrains-ides', 'https://www.jetbrains.com'),
  ('terminal', 'iTerm2',    'iterm2',    'https://iterm2.com'),
  ('terminal', 'Ghostty',   'ghostty',   'https://ghostty.org'),
  ('terminal', 'Warp',      'warp',      'https://warp.dev'),
  ('terminal', 'WezTerm',   'wezterm',   'https://wezterm.org'),
  ('terminal', 'Alacritty', 'alacritty', 'https://alacritty.org'),
  ('terminal', 'kitty',     'kitty',     'https://sw.kovidgoyal.net/kitty'),
  ('terminal', 'tmux',      'tmux',      'https://github.com/tmux/tmux')
on conflict (kind, slug) do nothing;
